manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/ReFil
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: keysmash
      remote: https://github.com/ReFil/refil-zmk-behaviour-modules
      revision: keysmash
    - name: sarcasm
      url: https://github.com/ReFil/refil-zmk-behaviour-modules
      revision: sarcasm
  self:
    path: config
